
name: blazorAppMono
region: ams
services:
#- dockerfile_path: Server/Dockerfile
  github:
    repo: lopesus/BlazorAppMono
    branch: master
    deploy_on_push: true
  source_dir: Server

  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bord-demo
  routes:
  - path: /
