name: blazorAppMono
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: lopesus/BlazorAppMono
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bord-demo
  routes:
  - path: /